### ISSUE TITLE
How to use APP_BASE_URL?

### ISSUE THREAD

**Issue by gperezalba** [Alethio/ethereum-lite-explorer#40]
Hi,

I'm trying to use the APP_BASE_URL in order to change og:tags in .html when using docker but I don't know how do I have to use it...

Thanks in advance

**Comment by use-strict** [comment]
You just pass it to `docker run` as an env variable:

`docker run -p 80:80 -e APP_BASE_URL="https:\/\/my.domain.tld" alethio/ethereu
m-lite-explorer`

I'm also getting some errors if I don't escape the slashes, so that's probably a bug which I'm going to investigate.

See also the examples here: https://github.com/Alethio/ethereum-lite-explorer#running-in-docker

**Comment by gperezalba** [comment]
But is it the way if I want to change the og:title for example? I though this was the purpose as it says "It is used ONLY in index.html for og:tags". Or maybe there's another way...

Thanks @use-strict

**Comment by gperezalba** [comment]
Okey I understand now... as it says "It is used ONLY in index.html for og:tags" I misunderstood it and tried to change other og:tags like og:title.

Thanks @use-strict

**Comment by use-strict** [comment]
Escaping issue will be fixed with https://github.com/Alethio/ethereum-lite-explorer/pull/41

> But is it the way if I want to change the og:title for example?

No, it's not. Env vars are there only for simple and very common customizations, like the node URL or the base URL. For more advanced customization, you can either mount a custom `config.json` or, if code changes are needed, you can build from source instead.

In the case of `og:title`, the string is the same as the application title, which is shown in the browser title bar. Because that is a localized string, it is taken from the `src/translation/*.json` files, which are packaged  together with the source code and not configurable. In this case you could fork the repo and build from source, but it is an open discussion whether such customization should be supported OOTB.
