### ISSUE TITLE
How to update translations?

### ISSUE THREAD

**Issue by deantheiceman** [Alethio/ethereum-lite-explorer#63]
What's the correct way to update translations and customise the appearance? It seems whenever I install the plugins everything is getting overwritten

**Comment by use-strict** [comment]
You can customize the translations if you [build from source](https://github.com/Alethio/ethereum-lite-explorer#building-from-source). You will need to edit the files under `src/app/translation`, before the `npm run build` step.

**Comment by deantheiceman** [comment]
This translation doesn't seem to be available, does `src/app/translation` overwrite the component translations?

```
Ethereum Lite Explorer
An open source Ethereum block explorer. Available on GitHub
```

**Comment by use-strict** [comment]
I see the problem. There is no *easy* way of changing those texts. As they are defined in one of the core plugins, you don't have direct access to them. So, until we make a proper fix, there are some things you could do right now:

The easy and ugly fix: directly editing the generated files under `dist/plugins/aleth.io/eth-common/js`. You'll have to manually find the bundle that contains the translations and change them in place. :(

There's also a slightly cleaner solution, but it's rather tedious for a simple text change. You could create a plugin that reimplements the [page://aleth.io/dashboard](https://github.com/Alethio/explorer-core-plugins/tree/master/src/app/shared/page/dashboard) object. You can start by reading the tutorial in the Alethio/cms repo readme. and then you could create a plugin that exports the new implementation of that object. You replace the page in the explorer's config with your own. I can provide more detailed steps if you want to go this way.

On the long run, we should also fix this properly on our side. We have a few possible options:

a. Have a way of overriding specific plugin translations from the main app translation files. This would still require forking the project and rebuilding. Not ideal
b. Load the translations at runtime from JSONs instead of relying on Webpack, so that we can mount a custom file instead / overwrite the files. This would allow overriding specific translations without having to rebuild anything and it would work in both Docker-based and build-from-source setups. This would however mean that we treat the translations as data files and so we'd need a versioning scheme for them.
c. (specific fix) Just move the title and subtitle into a separate module instead of hardcoding them in the page object. This way we can override the texts by replacing the module with a custom implementation, instead of cloning the whole page layout.

**Comment by use-strict** [comment]
Fixed. See https://github.com/Alethio/ethereum-lite-explorer#override-specific-text-strings-translations for instructions.

As per linked PR, option c) from above post was implemented.

**Comment by use-strict** [comment]
Also make sure to `npm install` after `git pull`. Some dependencies were updated.
